from dataclasses import dataclass
from enum import IntEnum
from typing import Self

class Fixity(IntEnum):
    INFIX = 1
    PREFIX = 2
    POSTFIX = 3
    MATCHFIX = 4
    NOFIX = 5

class Assoc(IntEnum):
    LEFT = 1
    RIGHT = 2
    NONE = 3

@dataclass(frozen=True)
class Symbol:
    """A symbol registered in an algebra block."""
    literal: str
    name: str
    binding_power: int = ...
    fixity: Fixity | None = ...
    assoc: Assoc | None = ...
    close: str | None = ...
    is_commutative: bool = ...
    is_associative: bool = ...
    is_idempotent: bool = ...
    is_involutive: bool = ...
    is_short_circuit: bool = ...
    identity_token: str | None = ...
    annihilator_token: str | None = ...
    def bp(self, n: int) -> Self: ...
    def left(self) -> Self: ...
    def right(self) -> Self: ...
    def noassoc(self) -> Self: ...
    def infix(self) -> Self: ...
    def prefix(self) -> Self: ...
    def postfix(self) -> Self: ...
    def matchfix(self, close: str) -> Self: ...
    def nofix(self) -> Self: ...
    def constant(self) -> Self: ...
    def commutative(self) -> Self: ...
    def associative(self) -> Self: ...
    def idempotent(self) -> Self: ...
    def involutive(self) -> Self: ...
    def shortCircuit(self) -> Self: ...
    def identity(self, e: str) -> Self: ...
    def annihilator(self, z: str) -> Self: ...
    def __init__(self, literal, name, binding_power=..., fixity=..., assoc=..., close=..., is_commutative=..., is_associative=..., is_idempotent=..., is_involutive=..., is_short_circuit=..., identity_token=..., annihilator_token=...) -> None: ...

@dataclass(frozen=True)
class RewriteRule:
    """A named algebraic identity (lhs, rhs) in an algebra's notation."""
    name: str
    lhs: str
    rhs: str
    def __init__(self, name, lhs, rhs) -> None: ...

@dataclass(frozen=True)
class AlgebraBlock:
    """A named collection of symbols and rewrite rules for one notational system."""
    name: str
    def add(self, item: Symbol | RewriteRule) -> Self: ...
    def lookup(self, literal: str) -> list[Symbol]: ...
    def __init__(self, name, _symbols=..., _rules=...) -> None: ...
